POST http://localhost:4000/register
Content-Type: application/json

{
    "name": "zizi",
    "email": "zizi@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}


###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "zizi@gmail.com",
    "password": "123456"
}

###
GET http://localhost:4000/auth


###
POST https://orange-red-panda-veil.cyclic.app/login
Content-Type: application/json

{
    "email": "zizi@gmail.com",
    "password": "123456"
}


###
GET https://orange-red-panda-veil.cyclic.app/auth